export const ALL_ACHIEVEMENTS = [
    {id: '1.1Done', icon: '1.1Done', desc: 'Nivel 1-1 Completado'},
    {id: '1.2Done', icon: '1.2Done', desc: 'Nivel 1-2 Completado'},
    {id: '1.3Done', icon: '1.3Done', desc: 'Nivel 1-3 Completado'},
    {id: '1.4Done', icon: '1.4Done', desc: 'Nivel 1-4 Completado'},
    {id: '1.5Done', icon: '1.5Done', desc: 'Nivel 1-5 Completado'},
    {id: '1.6Done', icon: '1.6Done', desc: 'Nivel 1-6 Completado'},
    {id: '1.1Estrellas', icon: '1.1Estrellas', desc: 'Nivel 1-1 Completado 3 Estrellas'},
    {id: '1.2Estrellas', icon: '1.2Estrellas', desc: 'Nivel 1-2 Completado 3 Estrellas'},
    {id: '1.3Estrellas', icon: '1.3Estrellas', desc: 'Nivel 1-3 Completado 3 Estrellas'},
    {id: '1.4Estrellas', icon: '1.4Estrellas', desc: 'Nivel 1-4 Completado 3 Estrellas'},
    {id: '1.5Estrellas', icon: '1.5Estrellas', desc: 'Nivel 1-5 Completado 3 Estrellas'},
    {id: '1.6Estrellas', icon: '1.6Estrellas', desc: 'Nivel 1-6 Completado 3 Estrellas'},
    {id: '2.1Done', icon: '2.1Done', desc: 'Nivel 2-1 Completado'},
    {id: '2.2Done', icon: '2.2Done', desc: 'Nivel 2-2 Completado'},
    {id: '2.3Done', icon: '2.3Done', desc: 'Nivel 2-3 Completado'},
    {id: '2.4Done', icon: '2.4Done', desc: 'Nivel 2-4 Completado'},
    {id: '2.5Done', icon: '2.5Done', desc: 'Nivel 2-5 Completado'},
    {id: '2.6Done', icon: '2.6Done', desc: 'Nivel 2-6 Completado'},
    {id: '2.1Estrellas', icon: '2.1Estrellas', desc: 'Nivel 2-1 Completado 3 Estrellas'},
    {id: '2.2Estrellas', icon: '2.2Estrellas', desc: 'Nivel 2-2 Completado 3 Estrellas'},
    {id: '2.3Estrellas', icon: '2.3Estrellas', desc: 'Nivel 2-3 Completado 3 Estrellas'},
    {id: '2.4Estrellas', icon: '2.4Estrellas', desc: 'Nivel 2-4 Completado 3 Estrellas'},
    {id: '2.5Estrellas', icon: '2.5Estrellas', desc: 'Nivel 2-5 Completado 3 Estrellas'},
    {id: '2.6Estrellas', icon: '2.6Estrellas', desc: 'Nivel 2-6 Completado 3 Estrellas'},
    {id: '1Done', icon: '1Done', desc: 'Completaste el primer mundo'},
    {id: '2Done', icon: '2Done', desc: 'Completaste el segundo mundo'},
    {id: '5Estrellas', icon: '5Estrellas', desc: 'Conseguiste 5 estrellas'},
    {id: '10Estrellas', icon: '10Estrellas', desc: 'Conseguiste 10 estrellas'},
    {id: '15Estrellas', icon: '15Estrellas', desc: 'Conseguiste 15 estrellas'},
    {id: '20Estrellas', icon: '20Estrellas', desc: 'Conseguiste 20 estrellas'},
    {id: '25Estrellas', icon: '25Estrellas', desc: 'Conseguiste 25 estrellas'},
    {id: '30Estrellas', icon: '30Estrellas', desc: 'Conseguiste 30 estrellas'},
    {id: '35Estrellas', icon: '35Estrellas', desc: 'Conseguiste 35 estrellas'},
    {id: '40Estrellas', icon: '40Estrellas', desc: 'Conseguiste 40 estrellas'},
    {id: '45Estrellas', icon: '45Estrellas', desc: 'Conseguiste 45 estrellas'},
    ]
