export const ALL_ACHIEVEMENTS = [
    {id: '1_1Done', icon: '1_1Done', desc: 'Nivel 1-1 Completado'},
    {id: '1_2Done', icon: '1_2Done', desc: 'Nivel 1-2 Completado'},
    {id: '1_3Done', icon: '1_3Done', desc: 'Nivel 1-3 Completado'},
    {id: '1_4Done', icon: '1_4Done', desc: 'Nivel 1-4 Completado'},
    {id: '1_5Done', icon: '1_5Done', desc: 'Nivel 1-5 Completado'},
    {id: '1_6Done', icon: '1_6Done', desc: 'Nivel 1-6 Completado'},
    {id: '1_1Estrellas', icon: '1_1Estrellas', desc: 'Nivel 1-1 Completado 3 Estrellas'},
    {id: '1_2Estrellas', icon: '1_2Estrellas', desc: 'Nivel 1-2 Completado 3 Estrellas'},
    {id: '1_3Estrellas', icon: '1_3Estrellas', desc: 'Nivel 1-3 Completado 3 Estrellas'},
    {id: '1_4Estrellas', icon: '1_4Estrellas', desc: 'Nivel 1-4 Completado 3 Estrellas'},
    {id: '1_5Estrellas', icon: '1_5Estrellas', desc: 'Nivel 1-5 Completado 3 Estrellas'},
    {id: '1_6Estrellas', icon: '1_6Estrellas', desc: 'Nivel 1-6 Completado 3 Estrellas'},
    {id: '2_1Done', icon: '2_1Done', desc: 'Nivel 2-1 Completado'},
    {id: '2_2Done', icon: '2_2Done', desc: 'Nivel 2-2 Completado'},
    {id: '2_3Done', icon: '2_3Done', desc: 'Nivel 2-3 Completado'},
    {id: '2_4Done', icon: '2_4Done', desc: 'Nivel 2-4 Completado'},
    {id: '2_5Done', icon: '2_5Done', desc: 'Nivel 2-5 Completado'},
    {id: '2_6Done', icon: '2_6Done', desc: 'Nivel 2-6 Completado'},
    {id: '2_1Estrellas', icon: '2_1Estrellas', desc: 'Nivel 2-1 Completado 3 Estrellas'},
    {id: '2_2Estrellas', icon: '2_2Estrellas', desc: 'Nivel 2-2 Completado 3 Estrellas'},
    {id: '2_3Estrellas', icon: '2_3Estrellas', desc: 'Nivel 2-3 Completado 3 Estrellas'},
    {id: '2_4Estrellas', icon: '2_4Estrellas', desc: 'Nivel 2-4 Completado 3 Estrellas'},
    {id: '2_5Estrellas', icon: '2_5Estrellas', desc: 'Nivel 2-5 Completado 3 Estrellas'},
    {id: '2_6Estrellas', icon: '2_6Estrellas', desc: 'Nivel 2-6 Completado 3 Estrellas'},
    {id: '1Done', icon: '1Done', desc: 'Completaste el primer mundo'},
    {id: '2Done', icon: '2Done', desc: 'Completaste el segundo mundo'},
    {id: '5Estrellas', icon: '5Estrellas', desc: 'Conseguiste 5 estrellas'},
    {id: '10Estrellas', icon: '10Estrellas', desc: 'Conseguiste 10 estrellas'},
    {id: '15Estrellas', icon: '15Estrellas', desc: 'Conseguiste 15 estrellas'},
    {id: '20Estrellas', icon: '20Estrellas', desc: 'Conseguiste 20 estrellas'},
    {id: '25Estrellas', icon: '25Estrellas', desc: 'Conseguiste 25 estrellas'},
    {id: '30Estrellas', icon: '30Estrellas', desc: 'Conseguiste 30 estrellas'},
    {id: '35Estrellas', icon: '35Estrellas', desc: 'Conseguiste 35 estrellas'},
    {id: '40Estrellas', icon: '40Estrellas', desc: 'Conseguiste 40 estrellas'},
    {id: '50Estrellas', icon: '50Estrellas', desc: 'Conseguiste 50 estrellas'},
    {id: '45Estrellas', icon: '45Estrellas', desc: 'Conseguiste 45 estrellas'},
    ]
